### PR TITLE
Add -l/--latest-deps option to update

### LINKED ISSUE #511: Enhancement request: mbed upgrade or mbed update -f
See conversation over in #505, it is a complete pain trying to develop a set of libraries as there is no way to tell mbed to just update everything to latest.  I recognise that there are dangers in doing this but, when actively developing a suite of libraries, a developer is perfectly aware of any changes he/she has made and just wants everything to stay in sync with what's archived; the only way to do that is to jump through all the directories and update each one individually, which is just horrible, almost unworkable, especially when one has to do it in the right order to avoid elements higher in the try *downgrading* the ones below again.

Hence, I request a new feature, which could either be `mbed upgrade` or a `-f` (==force) switch to `mbed update`.  The effect of this would be to update all the libraries to their latest versions, re-writing the `.lib` files as it goes.  A warning could be provided, something like "All libraries will be update to their latest versions, which may introduce incompatibilities; are you sure you want to continue? (y/n)"

### PR DESCRIPTION
**Pull request by theotherjimmy**
Resolves #511

### CODE REVIEW

**Comment by screamerbg** [comment]
@theotherjimmy Like the size the patch (really awesome!!), but not sure about the switch name. 
`-r/--recursive` leaves the impression that `update` doesn't work recursively. But `update` with no parameter would only update the current repository item and align sub-repositories to match the correct hash by recursively update them as well.

**Comment by bridadan** [comment]
@screamerbg Fair point. What if it was named `--recursively-update`? It's getting a bit lengthy now, but that may do a better job of describing the intended action.

**Comment by theotherjimmy** [comment]
@screamerbg Do you have an alternative suggestion? I think `-f/--force` was suggested in #511, but that does not really explain itself well.

**Comment by theotherjimmy** [comment]
`-u/--update-deps`?
`-i/--include-deps`?
`-i/--ignore-lib-files`?
`-m/--most-recent-deps`?

**Comment by theotherjimmy** [comment]
I kinda like `-l/--latest-deps` so I rewrote history to pretend that's what I was suggesting all along. :smile: What do you think of this version @screamerbg

**Comment by screamerbg** [comment]
And we have a winner gentleman :) LGTM

**Pull request merged**
