### PR TITLE
Fix a typo in mbed help

### PR DESCRIPTION
**Pull request by shakram02**
Fixed a small typo in help

### CODE REVIEW

**Comment by bridadan** [comment]
This PR will need a rebase to bring in the [fixes for the Circle CI configuration](https://github.com/ARMmbed/mbed-cli/pull/822).

**Comment by bridadan** [comment]
Hi @shakram02, could you rebase instead? The merge is bringing in extra changes to the history. If you need help with the rebase just let me know, thanks!

**Comment by shakram02** [comment]
Hey @bridadan, yes sure, sorry for the trouble as I'm still a newbie in making PRs for fixes :grimacing:. I hope it's fixed this way. Thanks for offering help!

**Comment by bridadan** [comment]
Not at all, thanks very much for the contribution!

**Pull request merged**
