### PR TITLE
Added tab completion for mbed cli on bash

### PR DESCRIPTION
**Pull request by mbartling**
FYI, this is only the bash file for tab completion. It is expected to go in some `DIR/etc/bash_completion.d/` directory. For example it goes into `/usr/local/etc/bash_completion.d/` on my mac.

Can someone help with the installation?

### CODE REVIEW

**Comment by SeppoTakalo** [comment]
700 lines of script for just a completion???
Sound like a lot, compared to what I did for `clitest.py` https://github.com/ARMmbed/mbed-clitest/blob/master/bash_completion/clitest

it looks like same piece of code is repeating over and over again.

**Comment by screamerbg** [comment]
@mbartling Please check @SeppoTakalo's comment. Perhaps his script can be reused.

**Comment by mbartling** [comment]
There is a lot of repetition in the code, but I did this for clarity vs brevity. @theotherjimmy what do you think?

**Comment by mbartling** [comment]
Also @SeppoTakalo, most of the lines look like this:

```
__mbedcomp "
    --help
    --all
    --message
    --verbose
    --very_verbose
    "
```

So the script looks way bigger than it actually is

**Comment by theotherjimmy** [comment]
@SeppoTakalo You did in ~77 lines about 1/10th of the amount of tab completion in this PR. If you look, things like you snippet is repeated for `sync`, `update`, etc. I don't think that his code being long should block this PR either. If it needs to be re-factored to be smaller/easier to maintain, then we can do that in the future too.

**Comment by screamerbg** [comment]
@mbartling Thanks for the PR. I agree with the simplicity vs brevity approach too. We still need to be aware about maintaining the list of options in the bash file. Perhaps this could be generated somehow?

**Comment by mbartling** [comment]
@screamerbg May be we should generate this file using the mbed-cli help

**Comment by mbartling** [comment]
This is what I have so far for a generation script

```
#!/usr/bin/env python

from collections import defaultdict
import re
import subprocess

commandRegex = r"^\s+(?P<command>\w+)\s+(?P<helptxt>[a-zA-Z ]*)$"  # This one extracts single commands and the help txt
subcommandRegex = r"^\s+(?P<command1>-+[\w_-]+(?P<modifier1>\s+[A-Z_-]+){0,1}(?P<command2>,\s+-+[\w_-]+(?P<modifier2>\s+[A-Z_-]+){0,1}){0,1})\s+(?P<helptxt>.*)$" # Gets just about everything

def getHelpTxt(command=None):
    if command:
        p = subprocess.Popen(["mbed", command, "-h"], stdout=subprocess.PIPE)
    else:
        p = subprocess.Popen(["mbed", "-h"], stdout=subprocess.PIPE)
    out, err = p.communicate()
    return out

if __name__ == '__main__':
    commands = defaultdict(defaultdict(list))
    helpTxt = getHelpTxt()
    #print helpTxt
    for line in helpTxt.split('\n'):
        match = re.search(commandRegex, line)
        if match:
            print "have match"
            print match.groupdict()
```

Both the regexes work

**Comment by screamerbg** [comment]
@mbartling This is great! Have you tried the generated output?

**Comment by mbartling** [comment]
Still working on it. Going to be out of town most of next week, but it shouldn't take too much longer to word for word generate the bash completion script

**Comment by BlackstoneEngineering** [comment]
LGTM?

**Comment by screamerbg** [comment]
@mbartling Can you add a paragraph and a link in README.md about tab competition and point to the extended documentation under tools/bash_completion/templates/README.md ?

**Comment by screamerbg** [comment]
@mbartling To clarify - I'd like some instructions that will allow every user to take advantage of this. E.g. generate file, put it in folder A on system X or in folder B on system Y.

**Comment by mbartling** [comment]
Will do this now

**Comment by screamerbg** [comment]
@mbartling Do you feel ready for this to be merged and released in 1.1?

**Comment by mbartling** [comment]
Yes to the current mbed bash completion script, but no to the generator. Still waiting on https://github.com/ARMmbed/mbed-cli/pull/460 and https://github.com/ARMmbed/mbed-os/pull/3993

**Comment by theotherjimmy** [comment]
@mbartling To be clear, Is this PR ready to be merged? If not, what are we waiting on?

**Comment by mbartling** [comment]
This PR can be merged as is, but the generator is not usable/integratabtle until https://github.com/ARMmbed/mbed-cli/pull/460 and https://github.com/ARMmbed/mbed-os/pull/3993 get merged

**Comment by screamerbg** [comment]
@mbartling Thanks for the PR. LGTM

**Pull request merged**
