### PR TITLE
Added warning message about Mbed OS Py3 compatability

### PR DESCRIPTION
**Pull request by cmonr**
New output:
```
$ mbed new .
[mbed] WARNING: Usage of Python 3 requires Mbed OS >= v5.9
---
[mbed] Creating new program "test" (git)
[mbed] Adding library "mbed-os" from "ssh://git@github.com/ARMmbed/mbed-os" at branch/tag "latest"
...
```

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
The warning is great.
But can we still catch the traceback error?

**Comment by cmonr** [comment]
@MarceloSalazar The particular traceback error that you hit will actually be resolved once https://github.com/ARMmbed/mbed-os/pull/7092 is merged. 

Continuing the issue conversation in here,

> This should be ok as quick/initial fix. My main interest is to catch the traceback error and display a message.

In what regard? Tracebacks can occur regardless of Python version.

**Comment by MarceloSalazar** [comment]
> The particular traceback error that you hit will actually be resolved once ARMmbed/mbed-os#7092 is merged.

I understand 7092 will fix the problem from 5.9+, which is good.

But I believe we'll still hit the error with <=5.8, unless we include a fix in CLI.
Is there anything we could do in CLI to catch the trace back for this particular use case?

**Comment by MarceloSalazar** [comment]
Btw, I'm happy to get this PR done and continue the conversation in 686.

**Comment by screamerbg** [comment]
@cmonr Could you expand the message to
```
WARNING: You're using Python 3 which requires Mbed OS 5.9 and above. If you're using Mbed OS 5.8 and earlier versions, you will get Python errors when compiling, testing and exporting.
```

**Comment by theotherjimmy** [comment]
@cmonr Could we print this message only on an error? that way we don't clutter up _perfectly working projects_

**Comment by theotherjimmy** [comment]
If it's harder, feel free to clutter things  up for now.

**Comment by screamerbg** [comment]
@theotherjimmy Let's get this in as a short-term solution. I'd like to add a mini-patch that detects the version by reusing the functionality from `mbed releases` and triggers a message if incompatibility is detected.

**Comment by screamerbg** [comment]
LGTM! Thanks

**Pull request merged**
