### PR TITLE
Restored `mbed target --supported` behavior

### PR DESCRIPTION
**Pull request by cmonr**
Issue reference: https://github.com/ARMmbed/mbed-cli/issues/557

### CODE REVIEW

**Comment by screamerbg** [comment]
The underlying problem is the introduction of the `matrix` parameter, which breaks for older releases of Mbed OS (5.1-5.5.7), basically all releases since July 2016 til July 2017. See #575.

This PR doesn't fix it (rather makes it worse). Appropriate fix should revert the `matrix` behavior introduced in #460 which breaks backwards compatiblity. Notice that make.py doesn't require the `matrix` param in mbed-os-5.5, therefore this looks like a safe approach

```
/tmp/1/test-program:$ mbed update mbed-os-5.5.7
/tmp/1/test-program:$ /usr/bin/python -u /private/tmp/1/test-program/mbed-os/tools/make.py -S 
+----------------------+-----------+-----------+-----------+-----------+-----------+
| Target               | mbed OS 2 | mbed OS 5 |    ARM    |  GCC_ARM  |    IAR    |
+----------------------+-----------+-----------+-----------+-----------+-----------+
| ARCH_PRO             | Supported | Supported | Supported | Supported | Supported |
+----------------------+-----------+-----------+-----------+-----------+-----------+

[snip]

Supported targets: 92

```

**Comment by theotherjimmy** [comment]
@cmonr @screamerbg We may be able to solve this by passing nothing when the argument to `-S/--supported` is `"matrix"`, as this is the default, and the old behavior.

**Comment by theotherjimmy** [comment]
@screamerbg Could you advise us on how to add a test that verifies that we do this in a backwards compatible way?

**Comment by screamerbg** [comment]
@cmonr Regarding how to test supported, add to circle something after `mbed new` like
`mbed targets -S`
`mbed compile -S`
`mbed update mbed-os-5.5.1`
`mbed targets -S`
`mbed compile -S`
`mbed update mbed-os-5.4.1`
`mbed targets -S`
`mbed compile -S`
`mbed update mbed-os-5.3.1`
`mbed targets -S`
`mbed compile -S`
`mbed update mbed-os-5.2.1`
`mbed targets -S`
`mbed compile -S`
`mbed update mbed-os-5.1.1`
`mbed targets -S`
`mbed compile -S`

**Comment by screamerbg** [comment]
@theotherjimmy Perhaps the same test can be invoked for `mbed export -S`?

**Comment by cmonr** [comment]
@screamerbg Well that's amusing. Regarding how to test, that's effectively what I'm doing right now, except I sped it up by having separate directories checked out to their appropriate versions.

**Comment by screamerbg** [comment]
@cmonr No pretty but it would do the job. You can make it look neat if you iterate through `mbed releases` (once it lands to master), checkout every `MINOR.1` release and run `mbed compile -S`, `mbed export -S` and `mbed target -S`

**Comment by cmonr** [comment]
@screamerbg Any particular reason why `MINOR.1` instead of `MINOR.0`? Just curious.

**Comment by cmonr** [comment]
Don't merge yet until tests are written (tomorrow).

Tested using `mbed compile -S`, `mbed target -S`, and `mbed toolchain -S`, and `mbed export -S` on mbed-os-5.x.0 versions, and latest version.

Looking for guidance from @mbartling on how to test for his features.

**Comment by screamerbg** [comment]
@cmonr if I'm not mistaken, one of the very first versions of mbed OS had the exporters broken in the x.0 release.

**Comment by screamerbg** [comment]
@cmonr Any update on this?

**Comment by cmonr** [comment]
@screamerbg The tests have been added in. I didn't find any issues with exporting from 5.1.0 and up.

**Pull request merged**
