### PR TITLE
Valgrind option added for unittests

### PR DESCRIPTION
**Pull request by AnttiKauppila**
Added option to select valgrind to be used with unittests

### CODE REVIEW

**Comment by AnttiKauppila** [comment]
Mbed OS needs to be updated first

**Comment by AnttiKauppila** [comment]
Python 2.7 error is "ERROR: Unknown Error: (128, 'Download failed!\nPlease try again later.')".
I cannot retrigger the build

**Comment by AnttiKauppila** [comment]
@mark-edgeworth @madchutney Who is in charge of this repo? Mbed OS PR has been merged and this wouold need a test restart + review from stakeholder(s).

**Comment by mark-edgeworth** [comment]
The mbed build tools team manage this repo. I've triggered a rebuild as requested.

**Comment by madchutney** [comment]
This doesn't look like it is related to Python 2.7, this test case actually does a lot more than the Python 3 tests. It is probably this way as the extra tests also run against older Mbed versions that do not support Python 3.

I believe the failure is related to a recent problem with a redirect from mbed.org.

> [mbed] Adding library "mbed" from "https://mbed.org/users/mbed_official/code/mbed/builds" at rev #3d0ef94e36ec
> [mbed] Downloading library build "3d0ef94e36ec" (might take a while)
> [mbed] ERROR: Unknown Error: (128, 'Download failed!\nPlease try again later.')

**Comment by AnttiKauppila** [comment]
What should I do with this now?

**Comment by AnttiKauppila** [comment]
It might work is mbed.org is replaced by os.mbed.org That is the place where it redirects

**Pull request merged**
