### PR TITLE
Caching feature

### PR DESCRIPTION
**Pull request by screamerbg**
This PR re-introduces repository caching as official/default mbed CLI feature:
- caching is enabled by default and uses the system/user default temp dir
- a user can override the cache location via the `CACHE` config setting
- a user can disable caching by setting up the `CACHE_DISABLED` config variable
- improved handling of mbed library builds (.bld/mbed 2.0)

Also fixes how cached repositories are handling across different protocols (e.g. cached ssh repo is cloned as https repo)

Reviewers:
- [ ] @sg- 
- [ ] @theotherjimmy 

Also cc @bridadan as this might have implications with the CI

### CODE REVIEW

**Comment by sg-** [comment]
LGTM 👍 

Looks to be enabled by default, is there a flag or global setting to disable caching?

**Comment by screamerbg** [comment]
@sg- Nice suggestion! Now implemented via the `cache_disabled` config option.

**Comment by sg-** [comment]
LGTM 👍

**Comment by bridadan** [comment]
@screamerbg Can't wait to see this guy in CI :smile:

**Pull request merged**
