### PR TITLE
Change the default build dir to 'build'

### PR DESCRIPTION
**Pull request by screamerbg**
This PR changes the default build dir from `.build` to `build`.

Also adds '.mbedignore' to ensure that contents of build are not scanned/included by the build system and reflects the change in the documentation.

Addressing #334 #206

@jaustin @MarceloSalazar @sg- @theotherjimmy

### CODE REVIEW

**Comment by bridadan** [comment]
@screamerbg Has this been tested when building tests? The test building process includes files from the build directory as source files.

**Comment by bridadan** [comment]
Also, I will need to update mbed-os CI will need to be updated to use the `build` directory now and not `.build`. I will look into this.

**Comment by screamerbg** [comment]
@bridadan That's why I'm raising these with you :)
CC @jupe

**Comment by sg-** [comment]
this needs to be ```BUILD```

**Comment by theotherjimmy** [comment]
Any particular reason for the capitalization @sg-?

**Comment by jupe** [comment]
CC: @miklis @marhil01 : this probably affected to our ci as well..

**Comment by sg-** [comment]
based on upcoming code base and API guidelines, any directory that is treated as magic will be capitalized.

**Comment by screamerbg** [comment]
Agree with @sg-. Now changed to 'BUILD'

**Comment by sg-** [comment]
LGTM 👍

**Comment by screamerbg** [comment]
@bridadan @jupe @miklis @marhil01 Can you confirm that the CIs are ready for this change?

**Comment by bridadan** [comment]
@screamerbg I've pinned the CI to use the current `mbed-cli` version for now (v0.9.5) so this change should not affect the Austin CI. I will migrate the jobs to the newest version of mbed-cli after this has been released.

**Comment by screamerbg** [comment]
@bridadan Thanks for the response.

@jupe @miklis @marhil01 The new mbed CLI will be released tomorrow. The PR was up for 11 days now so I hope you managed to transition the CI to either use the --build option or bind the CI to specific version of mbed CLI.

**Pull request merged**
