### PR TITLE
Added automatic uppercase conversion to --toolchain and --target.

### PR DESCRIPTION
**Pull request by korjaa**
Any comments on this?

related to #529

### CODE REVIEW

**Comment by JammuKekkonen** [comment]
PR seems to work as expected; both toolchain and target directories are now always uppercased.

**Comment by screamerbg** [comment]
@korjaa @JammuKekkonen Not sure that this will work as not all targets are upper case https://github.com/ARMmbed/mbed-os/blob/master/targets/targets.json

A possible solution is for the target folder parameter to be upper-cased when passed to the build tools (but not the target name), not on input.

**Comment by korjaa** [comment]
Aa, definitely true. Did cross my mind, but didn't know where to look for all targets.

**Comment by korjaa** [comment]
For me, it feels that the most logical way would be to make the target case sensitive, so that typing "k64F" would cause an error as it's not "K64F"

**Comment by screamerbg** [comment]
@theotherjimmy See above.

**Comment by bridadan** [comment]
+1 for enforcing consistent casing! I'd probably go with upper case for legacy reasons.

**Comment by theotherjimmy** [comment]
@korjaa You don't have to worry about the case of targets, as the mbed OS tools will convert as appropriate.

@screamerbg We _could_ make it an error, but with the "you got the case wrong" message. I'm not willing to make something that worked before stop working with no help to the user. Personally, I really like not having to use caps lock or the shift key when doing this stuff, but my preference may not be universal. I know that @sg- shares it though.

On that note, @korjaa You might want to drop this PR and propose something like that to the mbed OS tools. I think it should just be as simple as dropping the "force" from the type function. Let me know if you want assistance..

**Comment by korjaa** [comment]
@theotherjimmy Yes, the compilation works with both and that's the issue. It accepts the platform in anycase and then under `BUILD/` it creates a folder using that anycase name. Now, if you have a window open where your drag and drop your firmware, you could be using the previous build with a correct name from `BUILD/K64F` instead of the typoed build from `BUILD/k64F`. Or if you are using alias like below:
```
$ type mbed_flash 
mbed_flash is aliased to `cp BUILD/K64F/GCC_ARM/*.bin /media/jaakor01/DAPLINK/ && sync'
```.

Yes, I will close this PR as the uppercase doesn't really work with the non-uppercase targets.

**Pull request closed without merging**
