### PR TITLE
Added regex to remove inline oauth params from repo urls.

### PR DESCRIPTION
**Pull request by cmonr**
Reference bug https://github.com/ARMmbed/mbed-cli/issues/569

### CODE REVIEW

**Comment by janjongboom** [comment]
Why a regex and not a URL parser? Most URL parsers will parse the auth data out if straight away.

**Comment by theotherjimmy** [comment]
@janjongboom I updated this PR to use urlparse

**Comment by theotherjimmy** [comment]
With the example from #569, and the code change from this PR:

```python
>>> ref = 'https://77f0469f687b8b085d25cee082df6a89009aa0ee:x-oauth-basic@github.com/ARMmbed/mbed-os/#fc1836545dcc2fc86f03b01292b62bf2089f67c3'
>>> with_auth = urlparse(ref)
>>> print(with_auth._replace(netloc=with_auth.hostname).geturl())
https://github.com/ARMmbed/mbed-os/#fc1836545dcc2fc86f03b01292b62bf2089f67c3
```

**Comment by bridadan** [comment]
Nice work y'all 👍

**Pull request merged**
