### PR TITLE
Add app config switch

### PR DESCRIPTION
**Pull request by ConorPKeegan**
# Changes
* Add command line switch `--app-config` to specify the location of an app config file
* Specified file must be in the same format as `mbed_app.json`

# Example
This is an example use of the switch, where `test.json` is in the format of a `mbed_app.json` file
```
$ mbed test --compile -m K64F -t GCC_ARM --app-config test.json
```

# Dependencies
* This pull request depends on ARMmbed/mbed-os#2593

### CODE REVIEW

**Comment by ConorPKeegan** [comment]
@mazimkhan Please can you review this

**Comment by ConorPKeegan** [comment]
@bridadan To include the new changes from ARMmbed/mbed-os#2593 (the changes in `make.py`), which command needs to be changed, it seems to me that it would be `compile`?

**Comment by bridadan** [comment]
Yup! `mbed compile` goes to `make.py` and `mbed test` goes to `test.py` (only for `--compile` and `--compile-list`)

**Comment by ConorPKeegan** [comment]
@sg- @screamerbg Can we get this merged (depends on ARMmbed/mbed-os#2593)?

**Comment by screamerbg** [comment]
LGTM

**Pull request merged**
