### PR TITLE
python 2->3

### PR DESCRIPTION
**Pull request by davidhyman**
according to futurize
  \+ some minor fixes

Really we'll need something like workflows on circleci 2 to check the full test suite against Python3. Could do that as a separate ticket, or the same.

### CODE REVIEW

**Comment by davidhyman** [comment]
ref #601

**Comment by theotherjimmy** [comment]
@davidhyman I would like to have the workflows as part of this PR please. We may need to block this on support for `mbed compile`, `mbed test` and `mbed export`

**Comment by screamerbg** [comment]
Looks great! Thanks @davidhyman. This would have to wait until the other mbed OS tools need to support Python3 first as @theotherjimmy explained.

**Comment by cmonr** [comment]
@theotherjimmy @screamerbg Once this (https://github.com/ARMmbed/mbed-os/pull/6592) goes in, would anyone be opposed to moving this PR along?

**Comment by cmonr** [comment]
@davidhyman I wanted to check something with this PR.

The goal should be to add compatibility to make sure that mbed-cli can run with either Py2 or Py3. Does this PR do that? If so, would you mind changing the PR title to reflect this? (`python 2->3` to `python 2 & python 3`)

**Comment by screamerbg** [comment]
@davidhyman Could you please rebase this PR on top of master?

**Comment by cmonr** [comment]
Closing due to inactivity. Changes will be integrated into a separate PR for review.

**Pull request closed without merging**
