### PR TITLE
Bump version to 1.7.4

### PR DESCRIPTION
**Pull request by screamerbg**

### CODE REVIEW

**Comment by screamerbg** [comment]
@theotherjimmy Don't merge yet.

**Comment by theotherjimmy** [comment]
@screamerbg No problem. What are we waiting on?

**Comment by screamerbg** [comment]
@theotherjimmy Let's get this in and make a new release.

**Comment by theotherjimmy** [comment]
@screamerbg Would you like me to make the release?

**Comment by screamerbg** [comment]
Thanks. It's OK. I'll sort it out shortly.

**Pull request merged**
