### PR TITLE
Fix: Firmware flashing routine

### LINKED ISSUE #713: Program one of multiple platforms connected
This is an enhancement request.

I have many platforms connected to the USB port.

I'd like to compile and program one platform using this command:
```mbed compile -t <toolchain> -m <platform> -f```
This is very useful because finds the binary, detects the platform and programs it.

However, there is currently a limitation:
```[mbed] ERROR: Only 1 target board should be connected to your system.```

### PR DESCRIPTION
**Pull request by screamerbg**
Fix firmware flashing routine to flash the correct board/target connected to the user system.

Fixes #713 and #714

### CODE REVIEW

**Comment by cmonr** [comment]
Does this actually fix https://github.com/ARMmbed/mbed-cli/issues/713? I would expect that fix would end up removing line 1630.

**Comment by screamerbg** [comment]
@cmonr Perhaps re-read #713 and try it yourself :)

**Comment by theotherjimmy** [comment]
@screamerbg My reading of the code seems to indicate that it will flash and sterm to all matching connected boards in sequence. Is this the case?

**Comment by theotherjimmy** [comment]
@screamerbg @cmonr  The specific error message should only happen when using the `-t auto` or `-t detect` flags.

**Pull request merged**
